DROP TABLE IF EXISTS accessories CASCADE;
DROP TABLE IF EXISTS trainer_requests CASCADE;
DROP TABLE IF EXISTS trainer_ratings CASCADE;
DROP TABLE IF EXISTS trainer CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS client_accessories CASCADE;
DROP TABLE IF EXISTS client_machines CASCADE;
DROP TABLE IF EXISTS workout_exercise CASCADE;
DROP TABLE IF EXISTS workout CASCADE;
DROP TABLE IF EXISTS exercises CASCADE;
DROP TABLE IF EXISTS machines CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    gender INT NOT NULL,
    date_of_birth DATE NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    role INT NOT NULL DEFAULT 0
);

CREATE TABLE client (
    id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    height DOUBLE PRECISION NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    goal VARCHAR(200) NOT NULL,
    training_location INT NOT NULL DEFAULT 0,
    health_problems VARCHAR(100)
);

CREATE TABLE trainer (
    id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    specialization VARCHAR(100) NOT NULL,
    biography TEXT NOT NULL,
    license VARCHAR(100) NOT null
);

CREATE TABLE trainer_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id BIGINT REFERENCES users(id),
    trainer_id BIGINT REFERENCES users(id),
    status INT NOT NULL DEFAULT 0
);

CREATE TABLE accessories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL
);

CREATE TABLE machines (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE exercises (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    video_url VARCHAR(500),
    trainer_id BIGINT REFERENCES users(id),
    accessory_id BIGINT REFERENCES accessories(id),
    machine_id BIGINT REFERENCES machines(id)
);

CREATE TABLE client_accessories (
    client_id BIGINT REFERENCES client(id) ON DELETE CASCADE,
    accessory_id BIGINT REFERENCES accessories(id) ON DELETE CASCADE,
    PRIMARY KEY (client_id, accessory_id)
);

CREATE TABLE client_machines (
    client_id BIGINT REFERENCES client(id) ON DELETE CASCADE,
    machine_id BIGINT REFERENCES machines(id) ON DELETE CASCADE,
    PRIMARY KEY (client_id, machine_id)
);

CREATE TABLE workout (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL,
    note Text,
    trainer_id BIGINT REFERENCES users(id),
    client_id BIGINT REFERENCES users(id)
);

CREATE TABLE workout_exercise (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sets int not null,
    reps int not null,
    duration int not null,
    exercise_id BIGINT REFERENCES exercises(id),
    workout_id BIGINT REFERENCES workout(id)
);

CREATE TABLE trainer_ratings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rating int not null,
    comment TEXT,
    trainer_id BIGINT REFERENCES users(id),
    client_id BIGINT REFERENCES users(id)
)